name: main

on:
  push:
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        props:
        - Dockerfile: Dockerfile
          # suffix: alpine
        - Dockerfile: Dockerfile-ubuntu
          suffix: ubuntu
    steps:
      # -
      #   name: Checkout
      #   uses: actions/checkout@v2
      -
        name: Add tag suffix
        if: matrix.props.suffix
        run: |
          echo TAG_SUFFIX="-${{ matrix.props.suffix }}" >> $GITHUB_ENV
      -
        name: output
        run: echo $TAG_SUFFIX
      -
        name: Docker meta
        id: meta
        if: github.event_name != 'pull_request'
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          # NOTE: this org/repository matches the Docker registry paths
          images: |
            ${{ env.GITHUB_REPOSITORY }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}{{ env.TAG_SUFFIX }}
            type=semver,pattern={{major}}.{{minor}}{{ env.TAG_SUFFIX }}
            type=semver,pattern={{major}}{{ env.TAG_SUFFIX }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build + push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.props.Dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
